### Promise中的错误在哪个时机

```
setTimeout(()=>{
  console.log(12222);
})

new Promise(function (resolve, reject) {
  console.log(sdsd);
})

Promise.resolve().then(function () {
  console.log(1);
})

1 -> err - 12222

console.log(1) 和console.log(sdsd);在一个微任务栈内，所以比setTimeout早执行；
为什么1会早于err？ 应该和promise的实现有关，具体原因不知道；
```

